---
name: "Dr. Jekyll Action"
description: "A GitHub Action to build and deploy Jekyll documentation sites."
author: "Ryan Conrad <camalot@gmail.com>"

inputs:
  output_dir:
    description: "Directory where the built site will be output (default: _site)."
    required: false
    default: "_site"
  input_dir:
    description: "Directory containing the Jekyll source files (default: .)."
    required: false
    default: "."
  url:
    description: "URL for the Jekyll site (e.g. https://example.com)."
    required: false
    default: ""
  baseurl:
    description: "Base URL for the Jekyll site."
    required: false
    default: "/"

runs:
  using: "docker"
  image: "Dockerfile"
