# yaml-language-server: $schema=https://taskfile.dev/schema.json
---

version: '3'

vars: {}

tasks:
  docs:serve:
    desc: serve the documentation
    env:
      DRJEKYLL_DOCS_DIR: /workspace/drjekyll
      DRJEKYLL_SERVE: true
      INPUT_INPUT_DIR: docs
    cmds:
      - bash ./entrypoint.sh
    silent: true

  ruby:syntax:
    desc: check ruby syntax
    cmds:
      - cmd: |
          for file in /workspace/drjekyll/_plugins/*.rb; do
            CHECK_RUBY_SYNTAX="$(ruby -c "$file")"
            echo "$file -> $CHECK_RUBY_SYNTAX"
          done
