---
title: Dr. Jekyll
description: Documentation for the Dr. Jekyll GitHub Action, which builds and deploys Jekyll sites to GitHub Pages.
copyright: "&copy; 2026 Ryan Conrad. All rights reserved."

logo: /assets/images/icon.svg

# Aux links (top nav)
aux_links:
  "GitHub":
    - "https://github.com/camalot/drjekyll-action"

aux_links_new_tab: true
